---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - centos-8
      - debian-9
      - ubuntu-1804
    puppet:
      - puppet5
      - puppet6
      - ---puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Rakefile:
  changelog_project: puppet-module-cachefilesd
spec/acceptance/nodesets/debian-10.yml:
  delete: true
