---
.travis.yml:
  deploy: false
  docker_sets:
    - set: centos-8
      collection: puppet5
    - set: centos-8
      collection: puppet6
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
    - set: debian-9
      collection: puppet5
    - set: debian-9
      collection: puppet6
    - set: ubuntu-1604
      collection: puppet5
    - set: ubuntu-1604
      collection: puppet6
    - set: ubuntu-1804
      collection: puppet5
    - set: ubuntu-1804
      collection: puppet6
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Rakefile:
  changelog_project: puppet-module-cachefilesd
spec/acceptance/nodesets/debian-10.yml:
  delete: true
